sudo: true
dist: trusty
language: node_js
node_js:
  - 'stable'
  - '4.2.1'
addons:
  firefox: "50.0"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta
before_install:
  - 'npm config get registry'
  - 'npm config set registry http://registry.npmjs.org/'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'sleep 3' # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
install:
  - 'npm install --global grunt-cli bower yo generator-karma generator-angular'
  - 'npm install karma jasmine-core'
  - 'sudo apt-get install -y ruby ruby-dev make'
  - 'gem install compass'
  - 'npm update'
  - 'bower update'
  - 'node_modules/protractor/bin/webdriver-manager update --standalone --firefox'
  - 'sleep 5'
  - 'node_modules/protractor/bin/webdriver-manager start --standalone --firefox &'
  - 'sleep 5'
after_script:
- cat ./build/coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js
after_success: grunt coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7f1c48703628e3514bb6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
